### PR TITLE
update agp max version to 8.4.1

### PR DESCRIPTION
**Pull request by juliocbcotta**
closes https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1192 , I think.

Let me know if there is any other place to update.

### CODE REVIEW

**Comment by MGaetan89** [comment]
Maybe the 8.3.x line should be changed to 8.3.2 instead of 8.3.0-beta01?

**Comment by juliocbcotta** [comment]
> Maybe the 8.3.x line should be changed to 8.3.2 instead of 8.3.0-beta01?

I tried to do the least amount of changes to try to bring this to the main branch ASAP. If @autonomousapps thinks it is a good idea, I can do it.

**Comment by autonomousapps** [comment]
> Maybe the 8.3.x line should be changed to 8.3.2 instead of 8.3.0-beta01?

I am in favor of this. Thank you!

**Comment by juliocbcotta** [comment]
> > Maybe the 8.3.x line should be changed to 8.3.2 instead of 8.3.0-beta01?
> 
> I am in favor of this. Thank you!

done

**Review by MGaetan89 — APPROVED** [review]

**Review by autonomousapps — APPROVED** [review]

**Comment by juliocbcotta** [comment]
@autonomousapps , how to merge this? I don't see this option on github for my user, could you merge it ? Maybe release a new version too ?

**Pull request merged**
