### PR TITLE
Update test kit to use minSdk, targetSdk, compileSdk, and an equals after applicationId and namespace

### PR DESCRIPTION
**Pull request by j-roskopf**
I was using testkit to create an android project locally, and I didn't see anyway to overwrite the default values for the `android` block.

### CODE REVIEW

**Review by autonomousapps — COMMENTED** [review]
Thanks for the contribution. In which version of AGP were these property names updated?

**Comment by j-roskopf** [comment]
I'm not entirely sure the exact version! I created a new sample project and used AGP 7.0 and saw the properties were still deprecated, so I'm assuming pre 7.0 they were deprecated

**Comment by autonomousapps** [comment]
Thanks!

**Comment by j-roskopf** [comment]
@autonomousapps do you have an inkling to when this would be released?

**Comment by autonomousapps** [comment]
> @autonomousapps do you have an inkling to when this would be released?

Can't make any promises, so let's go with Soon ™️

**Pull request merged**
